with CUSTOMER
AS
(
    SELECT 
        *
    FROM {{ source('DEMO', 'stg__customer') }}
)
SELECT 
    C_CUSTKEY AS CUST_KEY,
	C_NAME AS CUST_NAME,
	C_ADDRESS AS ADDRESS,
	C_NATIONKEY AS NATION_KAY,
	C_PHONE AS PHONE_NO,
	C_ACCTBAL AS ACCOUNT_BALANCE,
	C_MKTSEGMENT AS MKT_SEGMENT,
	C_COMMENT AS COMMENT
FROM CUSTOMER