WITH LINEITEM
AS (
    SELECT 
        *
    FROM {{ source('DEMO', 'stg__lineitem') }}
)
SELECT
    L_ORDERKEY AS ORDER_KEY,
	L_PARTKEY PART_KEY,
	L_SUPPKEY AS SUPP_KEY,
	L_LINENUMBER AS LINE_NUMBER,
	L_QUANTITY AS QUANTITY,
	L_EXTENDEDPRICE AS EXTENDED_PRICE,
	L_DISCOUNT AS DISCOUNT,
	L_TAX AS TAX,
	L_RETURNFLAG AS RETURN_FLAG,
	L_LINESTATUS LINE_STATUS,
	L_SHIPDATE AS SHIP_DATE,
	L_COMMITDATE AS COMMIT_DATE,
	L_RECEIPTDATE AS RECEIPT_DATE,
	L_SHIPINSTRUCT AS SHIP_INSTRUCT,
	L_SHIPMODE AS SHIP_MODE,
	L_COMMENT AS COMMENT
FROM LINEITEM
