WITH ORDERS 
AS
(
    SELECT
    FROM {{ source('DEMO', 'stg__orders') }}
)
SELECT 
    O_ORDERKEY AS ORDER_KEY,
	O_CUSTKEY AS CUST_KEY,
	O_ORDERSTATUS AS ORDER_STATUS,
	O_TOTALPRICE TOTAL_PRICE,
	O_ORDERDATE ORDER_DATE,
	O_ORDERPRIORITY ORDER_PRIORITY,
	O_CLERK AS CLERK,
	O_SHIPPRIORITY SHIP_PRIORITY,
	O_COMMENT AS COMMENT
FROM ORDERS